name: J4 Sources Upload Crowdin Action
# Controls when the action will run. 
on:
  # Runs once a day at 6:42
  schedule:
    - cron:  '42 6 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
jobs:
  # This workflow contains a single job called "build"
  synchronize-with-crowdin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    
    # Runs the Crowdin action command - https://github.com/crowdin/github-action
    - name: crowdin action
      uses: crowdin/github-action@1.3.0
      with:
        # Upload sources to Crowdin
        upload_sources: true
        # Option to specify a path to the configuration file, without / at the beginning
        config: 'Configurations/Crowdin-J4-All.yml'
        # Use true for dryrun to test the run without actually processing anything
        dryrun_action: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
