name: J4 Translation Upload Crowdin Action
# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
jobs:
  # This workflow contains a single job called "build"
  synchronize-with-crowdin:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    
    # Runs the Crowdin action command - https://github.com/crowdin/github-action
    - name: crowdin action
      uses: crowdin/github-action@1.1.0
      with:
        # Upload sources to Crowdin
        upload_sources: false
        # Upload translations to Crowdin
        upload_translations: true
        # Define the languages to upload for translations
        upload_language: 'th'
        # Automatically approves uploaded translations
        auto_approve_imported: true
        # Automatically approves uploaded translations
        import_eq_suggestions: true
        # Make pull request of Crowdin translations
        download_translations: false
        # Only download translated strings
        skip_untranslated_strings: true
        # Include approved translations only in exported files. 
        # If not combined with --skip-untranslated-strings option, strings without approval are fulfilled with the source language'
        export_only_approved: true
        # Download translations with pushing to branch
        push_translations: true
        # Commit message for download translations
        commit_message: 'New Crowdin translations by Github Action'
        # To download translations to the specified version branch
        localization_branch_name: 'l10n_crowdin_translations'
        # Create pull request after pushing to branch
        create_pull_request: true
        # Option to specify a path to the configuration file, without / at the beginning
        config: 'Configurations/Crowdin-J4-All.yml'
        # Use true for dryrun to test the run without actually processing anything
        dryrun_action: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
